JQueryAjaxInMVC2/JQueryAjaxInMVC2/Models/ClassViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JQueryAjaxInMVC2.Models
{
    public class ClassViewModel
    {
        public int ClassID { get; set; }

        public int ClubID { get; set; }

        //[DisplayName("Instructor Name")]
        public int InstructorID { get; set; }

        [DisplayName("Class Date")]
        
        public System.DateTime ClassDate { get; set; }

        [DisplayName("Class Time")]
        public string ClassTime { get; set; }

        [DisplayName("GIAG Price")]
        public Nullable<decimal> ClassGIAGPrice { get; set; }

        [DisplayName("Venue Name")]
        public string VenueName { get; set; }

        [DisplayName(" Address Line 1")]
        public string AddressLine1 { get; set; }

        [DisplayName(" Address Line 2")]
        public string AddressLine2 { get; set; }
        public string Postcode { get; set; }


        [DisplayName("Class Name")]
        public string ClubName { get; set; }

        [DisplayName("Club Description")]
        public string ClubDescription { get; set; }

        [DisplayName("Club Membership")]
        public Nullable<decimal> ClubMembership { get; set; }


        [DisplayName("Instructor Name")]
        public string FirstName { get; set; }

        [DisplayName("Instructor Name")]
        public string LastName { get; set; }
    }
}

JQueryAjaxInMVC2/JQueryAjaxInMVC2/Controllers/ClassController.cs
using JQueryAjaxInMVC2.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JQueryAjaxInMVC2.Controllers
{
    public class ClassController : Controller
    {
        // GET: Class
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult ViewAll()
        {
            return View(GetAllClasses());
        }

        public IEnumerable<ClassViewModel> GetAllClasses()
        {
            using (DBModel db = new DBModel())
            {
                IEnumerable<Class> classList = db.Classes.ToList();
                //ClassViewModel classVM = new ClassViewModel();

                IEnumerable<ClassViewModel> classVMList = classList.Select(x => new ClassViewModel
                {
                    ClassID = x.ClassID,
                    ClubID = x.ClubID,
                    ClubName = x.Club.ClubName,
                    FirstName = x.Instructor.FirstName,
                    LastName = x.Instructor.LastName,
                    ClassDate = x.ClassDate,
                    ClassTime = x.ClassTime,
                    ClassGIAGPrice = x.ClassGIAGPrice,
                    VenueName = x.VenueName,
                    AddressLine1 = x.AddressLine1,
                    AddressLine2 = x.AddressLine2,
                    Postcode = x.Postcode
                }).ToList();


                // return db.Classes.ToList<Class>();
                return classVMList;
            }

        }


        public ActionResult AddOrEditClass(int id = 0)
        {
            DBModel db = new DBModel();
            Class classes = new Class();
            ClassViewModel model = new ClassViewModel();

            ViewBag.ClubList = new SelectList(GetClubList(), "ClubID", "ClubName");

            if (id != 0)
            {
                classes = db.Classes.SingleOrDefault(x => x.ClassID == id);
                model.ClassID = classes.ClassID;
                model.ClubID = classes.ClubID;
                model.InstructorID = classes.InstructorID;
                model.ClassDate = classes.ClassDate;
                model.ClassTime = classes.ClassTime;
                model.ClassGIAGPrice = classes.ClassGIAGPrice;
                model.VenueName = classes.VenueName;
                model.AddressLine1 = classes.AddressLine1;
                model.AddressLine2 = classes.AddressLine2;
                model.Postcode = classes.Postcode;

            }

            return View(model);
        }

        //These next two functions are for filtering the dropdownlist 
        // according to the club chosen and it gives a list of instructors for that club 
        public IEnumerable<Club> GetClubList()
        {
            DBModel db = new DBModel();

            IEnumerable<Club> clubs = db.Clubs.ToList();

            return clubs;
        }

        public ActionResult GetInstructorList(int clubID)
        {
            DBModel db = new DBModel();

            //this will get the firstName + lastName in the dropDown list
            var instructors = db.Instructors.Where(y => y.ClubID == clubID).Select(s => new { Text = s.FirstName + " " + s.LastName, Value = s.InstructorID }).ToList();
            ViewBag.InstructorOptions = new SelectList(instructors, "Value", "Text");

            return PartialView("InstructorOptionPartial");
        }


        [HttpPost]
        public ActionResult SaveClass(ClassViewModel model)
        {
            try
            {
                DBModel db = new DBModel();

                ViewBag.ClubList = new SelectList(GetClubList(), "ClubID", "ClubName");
                
                //this checks 'if' if something has been added or not if not then it saves changes
                if (model.ClassID > 0)
                {
                    
                    //Update
                    Class clas = db.Classes.SingleOrDefault(x => x.ClassID == model.ClassID);

                    clas.ClubID = model.ClubID;
                    clas.InstructorID = model.InstructorID;
                    clas.ClassDate = model.ClassDate;
                    clas.ClassTime = model.ClassTime;
                    clas.ClassGIAGPrice = model.ClassGIAGPrice;
                    clas.VenueName = model.VenueName;
                    clas.AddressLine1 = model.AddressLine1;
                    clas.AddressLine2 = model.AddressLine2;
                    clas.Postcode = model.Postcode;

                    db.SaveChanges();

                    return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "ViewAll", GetAllClasses()), message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);


                }
                else
                {
                    //This is going to insert data into the databse
                    Class classs = new Class();
                    classs.ClassID = model.ClassID;
                    classs.ClubID = model.ClubID;
                    classs.InstructorID = model.InstructorID;
                    classs.ClassDate = model.ClassDate;
                    classs.ClassTime = model.ClassTime;
                    classs.ClassGIAGPrice = model.ClassGIAGPrice;
                    classs.VenueName = model.VenueName;
                    classs.AddressLine1 = model.AddressLine1;
                    classs.AddressLine2 = model.AddressLine2;
                    classs.Postcode = model.Postcode;

                    db.Classes.Add(classs);
                    db.SaveChanges();

                    return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "ViewAll", GetAllClasses()), message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);

                }

            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }

        }


        public ActionResult DeleteClass(int id)
        {
            try
            {
                using (DBModel db = new DBModel())
                {
                    Class classes = db.Classes.Where(x => x.ClassID == id).FirstOrDefault<Class>();
                    db.Classes.Remove(classes);
                    db.SaveChanges();
                }
                //this will return the list of classes to  be displayed
                return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "ViewAll", GetAllClasses()), message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

JQueryAjaxInMVC2/JQueryAjaxInMVC2/Views/Class/AddOrEditClass.cshtml
@model JQueryAjaxInMVC2.Models.ClassViewModel
@{
    ViewBag.Title = "AddOrEditClass";
    Layout = null;
}

<script src="~/Scripts/jquery-1.12.4.js"></script>
<script src="~/Scripts/jquery-1.12.4.min.js"></script>

<script>
    $(document).ready(function () {

        $("#ClubID").change(function () {

            var clubID = $(this).val();
            debugger
            $.ajax({
                type: "Post",
                url: "/Class/GetInstructorList?ClubID=" + clubID,
                contentType: "html",
                success: function (response) {
                    debugger
                    $("#InstructorID").empty();
                    $("#InstructorID").append(response);
                }
            });

        });

    });


</script>


@using (Html.BeginForm("SaveClass", "Class", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return jQueryAjaxPostClass(this);", data_restUrl = Url.Action("AddOrEditClass", "Class", new { id = 0 }) }))//data-resetUrl
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ClassID)

        <div class="form-group">
            @Html.LabelFor(model => model.ClubName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (ViewBag.ClubList != null)
                {
                    @Html.DropDownListFor(model => model.ClubID, ViewBag.ClubList as SelectList, "--Select Club --", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ClubID, "", new { @class = "text-danger" })
                }
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               
                @Html.DropDownListFor(model => model.InstructorID, new SelectList(""), "--Select Instructor--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.InstructorID , "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            @Html.LabelFor(model => model.ClassDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-6">
                <div class="input-group date">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                    @Html.EditorFor(model => model.ClassDate, "", new { htmlAttributes = new { @class = " form-control datepicker", style = "width: 245px", placeholder = "Select Date" } })
                    
                </div>
            </div>
        </div>
         

        <div class="form-group">
            @Html.LabelFor(model => model.ClassTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClassTime, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Start - End time" } })
                @Html.ValidationMessageFor(model => model.ClassTime, "", new { @class = "text-danger" })
            </div>
        </div> 

        <div class="form-group">
            @Html.LabelFor(model => model.ClassGIAGPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">
                    <span class="input-group-addon">£</span>
                    @Html.EditorFor(model => model.ClassGIAGPrice, new { htmlAttributes = new { @class = "form-control", style = "width: 250px", placeholder = "Enter Price" } })
                </div>
                @Html.ValidationMessageFor(model => model.ClassGIAGPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VenueName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VenueName, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Venue name" } })
                @Html.ValidationMessageFor(model => model.VenueName, "", new { @class = "text-danger" })
            </div>
        </div> 

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine1, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Address line 1" } })
                @Html.ValidationMessageFor(model => model.AddressLine1, "", new { @class = "text-danger" })
            </div>
        </div> 

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine2, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Address line 2" } })
                @Html.ValidationMessageFor(model => model.AddressLine2, "", new { @class = "text-danger" })
            </div>
        </div> 

        <div class="form-group">
            @Html.LabelFor(model => model.Postcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Postcode, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Postcode" } })
                @Html.ValidationMessageFor(model => model.Postcode, "", new { @class = "text-danger" })
            </div>
        </div> 

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                @if (Model.ClassID != 0)
                {
                    <a class="btn btn-success" onclick="refreshAddNewClassTab('@Url.Action("AddOrEditClass", "Class", new { id = 0})', false)"><i class="fa fa-plus"></i>Add New Class</a>
                }
            </div>
        </div>


    </div>
}

@*<script src="~/Scripts/jquery-1.12.4.js"></script>
<script src="~/Scripts/jquery-1.12.4.min.js"></script>

<script>
    $(document).ready(function () {

        $("#ClubID").change(function () {

            var clubID = $(this).val();
            debugger
            $.ajax({
                type: "Post",
                url: "/Class/GetInstructorList?ClubID=" + clubID,
                contentType: "html",
                success: function (response) {
                    debugger
                    $("#InstructorID").empty();
                    $("#InstructorID").append(response);
                }
            });

        });

    });
   

</script>*@

    

JQueryAjaxInMVC2/JQueryAjaxInMVC2/Views/Class/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#firstTab">View All Classes</a></li>
    <li><a data-toggle="tab" href="#secondTab">Add New Class</a></li>
</ul>
<div class="tab-content">
    <div id="firstTab" class="tab-pane fade in active">@Html.Action("ViewAll")</div>
    <div id="secondTab" class="tab-pane fade in ">@Html.Action("AddOrEditClass")</div>
</div>


<link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css" rel="stylesheet" />


<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>


    <script>
        function activateClassjQueryTable() {
            $("#classTable").DataTable();
        }

        $(function () {
            activateClassjQueryTable();
        });

    </script>


<link href="~/Content/themes/base/datepicker.css" rel="stylesheet" />
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

    <script>

            $(function () {
                $(".datepicker").datepicker({
                    dateFormat: "yy/mm/dd",
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-1:+10"

                });

                //getter
                var dateFormat = $(".datepicker").datepicker("option", "dateFormat");

                //setter
                $(".datepicker").datepicker("option", "dateFormat", "yy/mm/dd");
            });
    </script>
} 

JQueryAjaxInMVC2/JQueryAjaxInMVC2/Views/Class/ViewAll.cshtml
@model IEnumerable<JQueryAjaxInMVC2.Models.ClassViewModel>
@{
    ViewBag.Title = "ViewAll";
    Layout = null;
}

<style>
    tr:hover {
        background-color: #f5f5f5;
    }
</style>

<table id="classTable" class="table  table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>Class Name</th>
            <th>Instructor Name</th>
            <th>Class Date</th>
            <th>Class Time</th>
            <th>GIAG Price</th>
            <th>Venue Name</th>
            <th>Address Line 1</th>
            <th>Address Line 2</th>
            <th>Postcode</th>
            <th></th>
           
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ClubName</td>
                <td>@item.FirstName @item.LastName</td>
                <td>@item.ClassDate.ToString("dd/MM/yyyy")</td>
                <td>@item.ClassTime</td>
                <td>@item.ClassGIAGPrice</td>
                <td>@item.VenueName</td>
                <td>@item.AddressLine1</td>
                <td>@item.AddressLine2</td>
                <td>@item.Postcode</td>
                <td>

                    <a class="btn btn-primary btn-sm" onclick="EditClass('@Url.Action("AddOrEditClass", "Class", new { id = @item.ClassID})')"><i class="fa fa-pencil fa-lg"></i></a>
                    <a class="btn btn-danger btn-sm" onclick="DeleteClass('@Url.Action("DeleteClass", "Class" , new { id = @item.ClassID})')"><i class="fa fa-trash fa-lg"></i></a>

                </td>
            </tr>

        }

    </tbody>
</table>