JQueryAjaxInMVC2/JQueryAjaxInMVC2/Models/Instructor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JQueryAjaxInMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instructor()
        {
            this.Classes = new HashSet<Class>();
            this.InstructorPasswords = new HashSet<InstructorPassword>();
        }
    
        public int InstructorID { get; set; }
        public int ClubID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Postcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class> Classes { get; set; }
        public virtual Club Club { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructorPassword> InstructorPasswords { get; set; }
    }
}

JQueryAjaxInMVC2/JQueryAjaxInMVC2/Models/InstructorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JQueryAjaxInMVC2.Models
{
    public class InstructorViewModel
    {
        public int InstructorID { get; set; }

       
        public int ClubID { get; set; }

        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [DisplayName("Email Address")]
        public string Email { get; set; }

        [DisplayName("Phone Number")]
        public string PhoneNumber { get; set; }

        [DisplayName("Address Line 1")]
        public string AddressLine1 { get; set; }

        [DisplayName("Address Line 2")]
        public string AddressLine2 { get; set; }

        public string Postcode { get; set; }

        [DisplayName("Club Name")]
        public string ClubName { get; set; }

        public string Username { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage ="Password is rrequired")]
        [DataType(DataType.Password)]
        [MinLength(6, ErrorMessage = "Minimum 6 characters required")]
        [MaxLength(10, ErrorMessage = "Maximum 10 characters required")]
        public string Password { get; set; }
        
    }
}

JQueryAjaxInMVC2/JQueryAjaxInMVC2/ViewModels/InstructorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JQueryAjaxInMVC2.ViewModels
{
    public class InstructorViewModel
    {
        public int InstructorID { get; set; }
        public int ClubID { get; set; }
        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [DisplayName("Email Address")]
        public string Email { get; set; }

        [DisplayName("Phone Number")]
        public string PhoneNumber { get; set; }

        [DisplayName("Address Line 1")]
        public string AddressLine1 { get; set; }

        [DisplayName("Address Line 2")]
        public string AddressLine2 { get; set; }

        public string Postcode { get; set; }

        [DisplayName("Club Name")]
        public string ClubName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }

    }
}

JQueryAjaxInMVC2/JQueryAjaxInMVC2/Controllers/InstructorController.cs
using JQueryAjaxInMVC2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JQueryAjaxInMVC2.Controllers
{
    public class InstructorController : Controller
    {
        // GET: Instructor
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewAllInstructors()
        {
            return View(GetAllInstructors());
        }


        public IEnumerable<InstructorViewModel> GetAllInstructors()
        {

            using (DBModel db = new DBModel())
            {
                IEnumerable<Instructor> instructorList = db.Instructors.ToList();

                IEnumerable<InstructorViewModel> instructorVMList = instructorList.Select(x => new InstructorViewModel
                {
                    InstructorID = x.InstructorID,
                    FirstName = x.FirstName,
                    LastName = x.LastName,
                    ClubID = x.ClubID,
                    ClubName = x.Club.ClubName,
                    Email = x.Email,
                    PhoneNumber = x.PhoneNumber,
                    AddressLine1 = x.AddressLine1,
                    AddressLine2 = x.AddressLine2,
                    Postcode = x.Postcode,
                    Username = db.InstructorPasswords.SingleOrDefault(y => y.InstructorID == x.InstructorID).Username
                }).ToList();

                return instructorVMList;
            }

        }


        public ActionResult AddOrEditInstructor(int id = 0)
        {
            DBModel db = new DBModel();

            IEnumerable<Club> clublist = db.Clubs.ToList();
            ViewBag.ClubList = new SelectList(clublist, "ClubID", "ClubName");

            InstructorViewModel model = new InstructorViewModel();

            if (id != 0)
            {
                Instructor instructor = db.Instructors.SingleOrDefault(x => x.InstructorID == id);
                model.InstructorID = instructor.InstructorID;
                model.FirstName = instructor.FirstName;
                model.LastName = instructor.LastName;
                model.ClubID = instructor.ClubID;
                model.PhoneNumber = instructor.PhoneNumber;
                model.Email = instructor.Email;
                model.AddressLine1 = instructor.AddressLine1;
                model.AddressLine2 = instructor.AddressLine2;
                model.Postcode = instructor.Postcode;

                InstructorPassword instrPswd = db.InstructorPasswords.SingleOrDefault(x => x.InstructorID == id);
                model.Username = instrPswd.Username;
                model.Password = instrPswd.Password;

            }

            return View(model);

        }



        [HttpPost]
        public ActionResult SaveInstructor(InstructorViewModel model)
        {
            try
            {
                DBModel db = new DBModel();

                IEnumerable<Club> clublist = db.Clubs.ToList();
                ViewBag.ClubList = new SelectList(clublist, "ClubID", "ClubName");

                if (model.InstructorID > 0)
                {
                    //Update
                    Instructor instruct = db.Instructors.SingleOrDefault(x => x.InstructorID == model.InstructorID);
                    instruct.FirstName = model.FirstName;
                    instruct.LastName = model.LastName;
                    instruct.ClubID = model.ClubID;
                    instruct.Email = model.Email;
                    instruct.PhoneNumber = model.PhoneNumber;
                    instruct.AddressLine1 = model.AddressLine1;
                    instruct.AddressLine2 = model.AddressLine2;
                    instruct.Postcode = model.Postcode;

                    db.SaveChanges();
                    int latestInstructorID = instruct.InstructorID;

                    var crypto = new SimpleCrypto.PBKDF2();

                    var encrpPass = crypto.Compute(model.Password);

                    InstructorPassword instrPswd = db.InstructorPasswords.SingleOrDefault(x => x.InstructorID == model.InstructorID);
                    instrPswd.Username = model.Username;
                    instrPswd.Password = encrpPass;
                    instrPswd.Salt = crypto.Salt;
                    instrPswd.InstructorID = latestInstructorID;

                    db.SaveChanges();

                    return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "ViewAllInstructors", GetAllInstructors()), message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);


                }
                else
                {
                    //Insert
                    Instructor instructor = new Instructor();
                    instructor.FirstName = model.FirstName;
                    instructor.LastName = model.LastName;
                    instructor.ClubID = model.ClubID;
                    instructor.Email = model.Email;
                    instructor.PhoneNumber = model.PhoneNumber;
                    instructor.AddressLine1 = model.AddressLine1;
                    instructor.AddressLine2 = model.AddressLine2;
                    instructor.Postcode = model.Postcode;

                    db.Instructors.Add(instructor);
                    db.SaveChanges();


                    int latestInstructorID = instructor.InstructorID;

                    InstructorPassword instructorPswd = new InstructorPassword();

                    var crypto = new SimpleCrypto.PBKDF2();

                    var encrpPass = crypto.Compute(model.Password);


                    instructorPswd.Username = model.Username;
                    instructorPswd.Password = encrpPass;
                    instructorPswd.Salt = crypto.Salt;
                    instructorPswd.InstructorID = latestInstructorID;

                    db.InstructorPasswords.Add(instructorPswd);
                    db.SaveChanges();

                    return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "ViewAllInstructors", GetAllInstructors()), message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);


                }


            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);

            }

        }


        //private bool IsValid(string username, string password)
        //{
        //    var crypto = new SimpleCrypto.PBKDF2();

        //    bool isValid = false;

        //    using (var db = new DBModel())
        //    {

        //    }



        //    return isValid;
        //}


        public ActionResult DeleteInstructor(int id)
        {
            try
            {
                DBModel db = new DBModel();


                InstructorPassword instructorPswd = db.InstructorPasswords.Where(x => x.InstructorID == id).FirstOrDefault<InstructorPassword>();
                db.InstructorPasswords.Remove(instructorPswd);
                db.SaveChanges();

                Instructor instructor = db.Instructors.Where(x => x.InstructorID == id).FirstOrDefault<Instructor>();
                db.Instructors.Remove(instructor);
                db.SaveChanges();


                return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "ViewAllInstructors", GetAllInstructors()), message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);


            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);

            }

            // return View();
        }
    }
 }

JQueryAjaxInMVC2/JQueryAjaxInMVC2/Views/Instructor/AddOrEditInstructor.cshtml
@model JQueryAjaxInMVC2.Models.InstructorViewModel

@{
    ViewBag.Title = "AddOrEditInstructor";
    Layout = null;
}


@using (Html.BeginForm("SaveInstructor", "Instructor", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return jQueryAjaxPostInstructor(this);", data_restUrl = Url.Action("AddOrEditInstructor", "Instructor", new { id = 0 }) }))//data-resetUrl
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="width: auto">

        @Html.ValidationSummary(true, "Data entered invalid, Please try again", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.InstructorID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter First name" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Last name" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Username" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", placeholder="Enter Password", Type ="password" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClubName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ClubID, ViewBag.ClubList as SelectList, "--Select Club--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClubID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Email" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Phone number" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine1, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Address line 1" } })
                @Html.ValidationMessageFor(model => model.AddressLine1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine2, new { htmlAttributes = new { @class = "form-control" , placeholder = "Enter Address line 2" } })
                @Html.ValidationMessageFor(model => model.AddressLine2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Postcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Postcode, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Postcode" } })
                @Html.ValidationMessageFor(model => model.Postcode, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id ="btnSave" type="submit" value="Save" class="btn btn-default" />
                @if(Model.InstructorID != 0)
                {
                    <a class="btn btn-success" onclick="refreshAddNewInstructorTab('@Url.Action("AddOrEditInstructor", "Instructor", new { id = 0})', false)"><i class="fa fa-plus"></i>Add New Instructor</a>
                }
            </div>
        </div>

    </div>
 } 

JQueryAjaxInMVC2/JQueryAjaxInMVC2/Views/Instructor/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#firstTab">View All Instructors</a></li>
    <li><a data-toggle="tab" href="#secondTab">Add New Instructor</a></li>
</ul>
<div class="tab-content">
    <div id="firstTab" class="tab-pane fade in active">@Html.Action("ViewAllInstructors")</div>
    <div id="secondTab" class="tab-pane fade in ">@Html.Action("AddOrEditInstructor")</div>
</div> 

<link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css" rel="stylesheet" />

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>

    <script>
        function activateInstructorjQueryTable() {
            $("#instructorTable").DataTable();
        }

        $(function () {
            activateInstructorjQueryTable();
        });

    </script>

}

 

JQueryAjaxInMVC2/JQueryAjaxInMVC2/Views/Instructor/ViewAll.cshtml
@model IEnumerable<JQueryAjaxInMVC2.ViewModels.InstructorViewModel>
@{
    ViewBag.Title = "ViewAll";
    Layout = null;
}

<link href="~/Content/bootstrap.css" rel="stylesheet"/>


    <table class="table" id="instructorTable">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Club Name</th>
                <th>Username</th>
                <th>Email Address</th>
                <th>Phone Number</th>
                <th>Address Line 1</th>
                <th>Address Line 2</th>
                <th>Postcode</th>
                <th></th>

            </tr>
        </thead>
        <tbody>
            
            @foreach(var item  in Model)
            {
                <tr>
                    <td>@item.FirstName</td>
                    <td>@item.LastName</td>
                    <td>@item.ClubName</td>
                    <td>@item.Username</td>
                    <td>@item.Email</td>
                    <td>@item.PhoneNumber</td>
                    <td>@item.AddressLine1</td>
                    <td>@item.AddressLine2</td>
                    <td>@item.Postcode</td>
                    <td>
                        <a class="btn btn-primary btn-sm" onclick="Edit('@Url.Action("AddOrEditInstructor", "Instructor", new { id =@item.InstructorID})')"><i class="fa fa-pencil fa-lg"></i></a>
                        <a class="btn btn-danger btn-sm" onclick="Delete('@Url.Action("Delete", "Instructor" , new { id =@item.InstructorID})')"><i class="fa fa-trash fa-lg"></i></a>

                    </td>
                </tr>
            }
        </tbody>
    </table>

JQueryAjaxInMVC2/JQueryAjaxInMVC2/Views/Instructor/ViewAllInstructors.cshtml
@model IEnumerable<JQueryAjaxInMVC2.Models.InstructorViewModel>

@{
    ViewBag.Title = "ViewAllInstructors";
    Layout = null;
}

<style>
    tr:hover {
        background-color: #f5f5f5;
    }
</style>

<table id="instructorTable" class="table table-bordered" style="width:100%" >
    <thead>
            <tr>
                <th>Name</th>
                <th>Club Name</th>
                <th>Username</th>
                <th>Email Address</th>
                <th>Phone Number</th>
                <th>Address Line 1</th>
                <th>Address Line 2</th>
                <th>Postcode</th>
                <th></th>

            </tr>
     </thead>
       <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.FirstName @item.LastName</td>
                        <td>@item.ClubName</td>
                        <td>@item.Username</td>
                        <td>@item.Email</td>
                        <td>@item.PhoneNumber</td>
                        <td>@item.AddressLine1</td>
                        <td>@item.AddressLine2</td>
                        <td>@item.Postcode</td>
                        <td>
                            <a class="btn btn-primary btn-sm" onclick="EditInstructor('@Url.Action("AddOrEditInstructor", "Instructor", new { id = @item.InstructorID })')"><i class="fa fa-pencil fa-lg"></i></a>
                            <a class="btn btn-danger btn-sm" onclick="DeleteInstructor('@Url.Action("DeleteInstructor", "Instructor", new { id = @item.InstructorID })')"><i class="fa fa-trash fa-lg"></i></a>

                        </td>
                    </tr>
                }
        </tbody>
</table>