JQueryAjaxInMVC2/JQueryAjaxInMVC2/Controllers/ClubController.cs
using JQueryAjaxInMVC2.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JQueryAjaxInMVC2.Controllers
{
    public class ClubController : Controller
    {

        // GET: Club
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewAll()
        {
            return View(GetAllClubs());
        }

        IEnumerable<Club> GetAllClubs()
        {
            using (DBModel db = new DBModel())
            {
                return db.Clubs.ToList<Club>();
            }

        }

        public ActionResult AddOrEditClub(int id = 0)
        {
            Club club = new Club();
            if (id != 0)
            {
                using (DBModel db = new DBModel())
                {
                    club = db.Clubs.Where(x => x.ClubID == id).FirstOrDefault<Club>();
                }
            }
            return View(club);
        }

        [HttpPost]
        public ActionResult SaveClub(Club club)
        {
            try
            {
                using (DBModel db = new DBModel())
                {
                    //this checks 'if' if something has been added or not if not then it saves changes
                    if (club.ClubID == 0)
                    {
                        db.Clubs.Add(club);
                        db.SaveChanges();

                        return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "ViewAll", GetAllClubs()), message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);

                    }
                    else
                    {
                        db.Entry(club).State = EntityState.Modified;
                        db.SaveChanges();

                        return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "ViewAll", GetAllClubs()), message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);

                    }
                }

            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                using (DBModel db = new DBModel())
                {
                    Club club = db.Clubs.Where(x => x.ClubID == id).FirstOrDefault<Club>();
                    db.Clubs.Remove(club);
                    db.SaveChanges();
                }
                //this will return the list of clubs to  be displayed
                return Json(new { success = true, html = GlobalClass.RenderRazorViewToString(this, "ViewAll", GetAllClubs()), message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

JQueryAjaxInMVC2/JQueryAjaxInMVC2/Views/Shared/InstructorOptionPartial.cshtml
<option value="">--Select Instructor--</option>
@if (ViewBag.InstructorOptions != null)
{
    foreach (var item in ViewBag.InstructorOptions)
    {
        <option value="@item.Value">@item.Text</option>
    }
}

JQueryAjaxInMVC2/JQueryAjaxInMVC2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    @* if issues starts to happen comment out these 2 below *@
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>*@
    

</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top" >
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a class="navbar-brand" href="#">Martial Arts Class Bookings</a>
                </div>

            <div class="navbar-collapse collapse" id=".navbar-collapse">
               
                @if (User.Identity.IsAuthenticated)
                {

                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Clubs", "Index", "Club")</li>
                        <li>@Html.ActionLink("Instructors", "Index", "Instructor")</li>
                        <li>@Html.ActionLink("Classes", "Index", "Class")</li>
                        <li>@Html.ActionLink("Bookings", "ViewBookingList", "BookingList")</li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Welcome: @User.Identity.Name</a></li>
                        <li>@Html.ActionLink("Log out", "LogOut", "User")</li>
                    </ul>

                }
                else
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Login", "LogIn", "User")</li>
                    </ul>

                }


             </div>
         </>
    </div>




        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Martial Arts Class Booking Management Application</p>
            </footer>
        </div>

        <div class="loaderbody" id="loaderbody">
            <div class="loader"></div>
        </div>
   
     <script src="~/Scripts/jquery-1.12.4.min.js"></script>
     <script src="~/Scripts/jquery.validate.min.js"></script>
     <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>  
    @*<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>*@

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        

    
        <script src="~/Scripts/Scripts.js"></script>
        <script src="~/Scripts/notify.min.js"></script>
    

    </body>
    </html>

JQueryAjaxInMVC2/JQueryAjaxInMVC2/Views/Shared/_LayoutCustomer.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Customer View Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    @* if issues starts to happen comment out these 2 below *@
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>*@

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css" />
    <script scr="https://code.jquery.com/jquery-3.2.1.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
</head>
<body>

<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="#"><img alt="Brand" src="~/Content/Images/logo.jpg" height="30" width="30"></a>

        </div>

        <div class="navbar-collapse collapse" id=".navbar-collapse">
            
            <ul class="nav navbar-nav">
                <li><a href="@Url.Action("Index", "Customer")" class="btn btn-lg">
                    <span class="glyphicon glyphicon-home" style="color:burlywood"></span>  Home </a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">                
              
                @if (Request.IsAuthenticated)
                {
                    @*<li>@Html.Encode(User.Identity.Name)</li>*@
                    @*<li>@Html.ActionLink("Sign out", "Logout", "Customer")</li>*@
                    <li><a href="#"><strong> Welcome: @User.Identity.Name</strong></a></li>

                    <li>
                        <a href="@Url.Action("CustomerLogout", "Customer")" class="btn btn-lg">
                            <span class="glyphicon glyphicon-log-out" style="color:burlywood"></span>  Sign out
                        </a>
                    </li>
                }
                else
                {

                    <li>
                        <a href="@Url.Action("RegisterOrEdit", "Customer")" class="btn btn-lg">
                            <span class="glyphicon glyphicon-plus-sign" style="color:burlywood"></span>  Register
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("customerLogin", "Customer")" class="btn btn-lg">
                            <span class="glyphicon glyphicon-log-in" style="color:burlywood"></span>  Login
                        </a>
                    </li>
                }
            </ul>
        </div>
    </div>
</div>

    <div  class="container body-content"> 
        @RenderBody()

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Martial Art Class Booking Application</p>
        </footer>
    </div>

    @*<div class="loaderbody" id="loaderbody">
        <div class="loader"></div>
    </div>*@

    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script src="~/Scripts/Scripts.js"></script>
    <script src="~/Scripts/notify.min.js"></script>

</body>
</html>