JQueryAjaxInMVC2/JQueryAjaxInMVC2/Controllers/UserController.cs
using JQueryAjaxInMVC2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace JQueryAjaxInMVC2.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogIn(InstructorPassword instructor)
        {
            DBModel db = new DBModel();
            if (ModelState.IsValid)
            {
                if(IsValid(instructor.Username, instructor.Password))
                {
                    FormsAuthentication.SetAuthCookie(instructor.Username, false);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                   
                   ModelState.AddModelError("", "Invalid user!");
                    
                }

            }
            return View(instructor);
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            //return RedirectToAction("LogOut", "User");
            return View();
        }



        private bool IsValid(string username, string password)
        {
            var crypto = new SimpleCrypto.PBKDF2();

            bool isValid = false;

            using (var db = new DBModel())
            {
                var instructor = db.InstructorPasswords.FirstOrDefault(u => u.Username == username);

                if(instructor != null)
                {
                    if(instructor.Password == crypto.Compute(password, instructor.Salt))
                    {
                        isValid = true;
                    }
                }
            }
                return isValid;

        } 

    }
}

JQueryAjaxInMVC2/JQueryAjaxInMVC2/Views/User/Index.cshtml
@{
    ViewBag.Title = "Index";
    
  }

<h2>Index</h2>

JQueryAjaxInMVC2/JQueryAjaxInMVC2/Views/User/LogIn.cshtml
@model JQueryAjaxInMVC2.Models.InstructorPassword
@{
    ViewBag.Title = "Log in";
    Layout = null;
}

<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable = no" name="viewport">

<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<style type="text/css">
    h2{text-align:center;}
    h2{text-align:center;}
    h3{text-align:center;}
</style>


@using (Html.BeginForm())
{
    <br />
    <h2>Welcome to Martial Arts Classes Booking Management</h2>
    <h2>Please login!</h2>

   <h3>@Html.ValidationSummary(true, "Login failed. Check your login details.", new { @class = "text-danger" })</h3>

    <div class="container" style="margin-top:10%">
        <div class="row">
            <div class="col-md-4 col-md-offset-4 alert alert-info">
                <h3 class="text-center">Login</h3>
                <form id="loginForm">                  

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                @Html.EditorFor(u => u.Username, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Username" } })
                            </div>
                            @Html.ValidationMessageFor(u => u.Username, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                @Html.EditorFor(u => u.Password, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Password", Type = "password" } })
                            </div>
                            @Html.ValidationMessageFor(u => u.Password, "", new { @class = "text-danger" })

                        </div>

                </form>

                <div class="form-group">

                    <button class="btn btn-info form-control" type="submit"><i class="glyphicon glyphicon-log-in"></i> Login</button>
                </div>

            </div>

        </div>

    </div>

}

JQueryAjaxInMVC2/JQueryAjaxInMVC2/Views/User/LogOut.cshtml
@{
    ViewBag.Title = "LogOut";
    Layout = null;
}

<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable = no" name="viewport">

@*<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />*@

<style type="text/css">
    h2 {
        text-align: center;
    }

    h2 {
        text-align: center;
    }

     div {
        text-align: center;
    }
</style>

<h2>Thank you for using our system</h2>
<h2>To log back in click the login button below</h2>



<div>
     <input type="button" value="Login" class="btn btn-info btn-lg btn-block btn-huge" onclick="location.href='@Url.Action("Login", "User")'" />
   
</div>	       